name: Build master

on: [push, pull_request]

jobs:
  env:
    # Work around https://github.com/actions/setup-dotnet/issues/29
    DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
    CI: true
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [3.1.301]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Set version
      id: set-version
      run: echo "::set-env name=PACKAGE_VERSION::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"
    - name: Build
      run: |
        dotnet tool restore
        dotnet fornax build
        dotnet dotnet-octo pack --id jeremyabbott.dev --version $PACKAGE_VERSION --format Zip --basePath ./_public/ --outFolder ./publish
    - name: Publish
      run: |
        dotnet dotnet-octo push --package "./publish/jeremyabbott.dev.$PACKAGE_VERSION.zip" --server "${{ secrets.OCTOPUS_SERVER }}" --apiKey "${{ secrets.OCTOPUS_API_KEY }}"